// `stream`: the negative side of `list`. The module carries the context,
// so nothing here repeats it: `stream::map`, not `map`.
//
// A menu is codata: only the demanded branch ever runs, so an infinite
// structure is just a menu that offers itself again. `Stream` is the
// coinductive mirror of `List`. There is no `impl Display for Stream` — an
// infinite structure cannot print whole; the honest form is
// `⟨(s, n) | take | fmt`.

mod stream {
    use list::List::*;

    pub menu Stream<+T> {
        head: T,
        tail: Stream<T>,
    }

    pub fn repeat<+T>(x: T) -> Stream<T> {
        mu Stream {
            head <= ⟨x | head⟩,
            tail <= ⟨x | repeat | tail⟩,
        }
    }

    pub fn count_from(n: i64) -> Stream<i64> {
        mu Stream {
            head <= ⟨n | head⟩,
            tail <= ⟨(n, 1) | add | count_from | tail⟩,
        }
    }

    pub fn map<+A, +B, E>(f: (A -> B / {..E}), s: Stream<A>) -> Stream<B> / {..E} {
        mu Stream {
            head <= ⟨s.head | f | head⟩,
            tail <= ⟨(f, s.tail) | map | tail⟩,
        }
    }

    // The bridge back to data: the first `n` elements, as a list.
    pub fn take<+T>(s: Stream<T>, n: i64) -> list::List<T> {
        match (⟨(n, 0) | le) { true => { Nil }, _ => { Cons(s.head, ⟨(s.tail, (⟨(n, 1) | sub)) | take) } }
    }

    // A stream is as often generated by a step function as by recursion.
    // `unfold` is the general form — each step answers an element and the
    // seed the rest is built from — and `iterate` the case where the state
    // *is* the element. Only the demanded arm runs, so the step runs once
    // per demand.

    pub fn unfold<+S, +T>(step: (S -> (T, S)), seed: S) -> Stream<T> {
        mu Stream {
            head <= ⟨(⟨seed | step).0 | head⟩,
            tail <= ⟨(step, (⟨seed | step).1) | unfold | tail⟩,
        }
    }

    pub fn iterate<+T>(f: (T -> T), x: T) -> Stream<T> {
        mu Stream {
            head <= ⟨x | head⟩,
            tail <= ⟨(f, ⟨x | f) | iterate | tail⟩,
        }
    }

    pub fn zip<+A, +B>(a: Stream<A>, b: Stream<B>) -> Stream<(A, B)> {
        mu Stream {
            head <= ⟨(a.head, b.head) | head⟩,
            tail <= ⟨(a.tail, b.tail) | zip | tail⟩,
        }
    }

    // Unlike the others this forces as it goes: `n` demands happen here
    // rather than at the first demand of the result.
    pub fn drop<+T>(s: Stream<T>, n: i64) -> Stream<T> {
        match (⟨(n, 0) | le) { true => { s }, _ => { ⟨(s.tail, (⟨(n, 1) | sub)) | drop } }
    }
}
