// `stream`: the negative side of `list`. The module carries the context,
// so nothing here repeats it: `stream::map`, not `map`.
//
// A menu is codata: only the demanded branch ever runs, so an infinite
// structure is just a menu that offers itself again. `Stream` is the
// coinductive mirror of `List`. There is no `impl Display for Stream` — an
// infinite structure cannot print whole; the honest form is
// `<(s, n) | take | fmt`.

mod stream {
    use list::List::*;

    pub menu Stream<+T, E> / {..E} {
        head: T,
        tail: Delayed<Stream<T, ..E>, ..E>,
    }

    pub fn repeat<+T>(x: T) -> Stream<T> {
        mu Stream {
            head <= <x | head>,
            tail <= <x | repeat | tail>,
        }
    }

    pub fn count_from(n: i64) -> Stream<i64> {
        mu Stream {
            head <= <n | head>,
            tail <= <(n, 1) | add | count_from | tail>,
        }
    }

    pub fn map<+A, +B, E>(f: (A -> B / {..E}), s: Delayed<Stream<A, ..E>, ..E>) -> Stream<B, ..E> {
        mu Stream {
            head <= <s.head | f | head>,
            tail <= <(f, s.tail) | map | tail>,
        }
    }

    // The bridge back to data: the first `n` elements, as a list.
    pub fn take<+T, E>(s: Delayed<Stream<T, ..E>, ..E>, n: i64) -> list::List<T> / {..E} {
        match (<(n, 0) | le) {
            True => { Nil },
            _ => { Cons(s.head, <(s.tail, <(n, 1) | sub) | take) },
        }
    }

    // A stream is as often generated by a step function as by recursion.
    // `unfold` is the general form — each step answers an element and the
    // seed the rest is built from — and `iterate` the case where the state
    // *is* the element. Only the demanded arm runs, so the step runs once
    // per demand.

    pub fn unfold<+S, +T, E>(step: (S -> (T, S) / {..E}), seed: S) -> Stream<T, ..E> {
        mu Stream {
            head <= <(<seed | step).0 | head>,
            tail <= <(step, (<seed | step).1) | unfold | tail>,
        }
    }

    pub fn iterate<+T, E>(f: (T -> T / {..E}), x: T) -> Stream<T, ..E> {
        mu Stream {
            head <= <x | head>,
            tail <= <(f, <x | f) | iterate | tail>,
        }
    }

    pub fn zip<+A, +B, E>(
        a: Delayed<Stream<A, ..E>, ..E>,
        b: Delayed<Stream<B, ..E>, ..E>,
    ) -> Stream<(A, B), ..E> {
        mu Stream {
            head <= <(a.head, b.head) | head>,
            tail <= <(a.tail, b.tail) | zip | tail>,
        }
    }

    // Unlike the others this forces as it goes: `n` demands happen here
    // rather than at the first demand of the result.
    pub fn drop<+T, E>(s: Delayed<Stream<T, ..E>, ..E>, n: i64) -> Stream<T, ..E> / {..E} {
        match (<(n, 0) | le) {
            True => {
                let+ ready = s;
                ready
            },
            _ => { <(s.tail, <(n, 1) | sub) | drop },
        }
    }
}
